<?php

namespace AccountService\Common;

class CacheKey {
    
    const CORE_CONFIG_DATA_ID           = "ACCOUNT.CORE_CONFIG_DATA.ID";
    const CORE_CONFIG_DATA_CODE         = "ACCOUNT.CORE_CONFIG_DATA.CODE";
    const CORE_CONFIG_DATA_CODE_ENTITY  = "ACCOUNT.CORE_CONFIG_DATA.CODE_ENTITY";

    const MESSAGE_COMMON_CODE           = "ACCOUNT.MESSAGE_COMMON.CODE";
    
    const NEWS_CATEGORY_NEWS            = "ACCOUNT.NEWS_CATEGORY.NEWS";
    const NEWS_CATEGORY_VIDEO           = "ACCOUNT.NEWS_CATEGORY.VIDEO";
    const NEWS_CATEGORY_ID              = "ACCOUNT.NEWS_CATEGORY.ID";
    const NEWS_CATEGORY_CODE            = "ACCOUNT.NEWS_CATEGORY.CODE";


    const DEDU_CONFIG					= "ACCOUNT.DEDU_CONFIG";

    const NEWS_DETAIL                   = "ACCOUNT.NEWS_DETAIL";
    
    const BOX_ID                        = "ACCOUNT.BOX.ID";
    const BOX_TYPE                      = "ACCOUNT.BOX.TYPE";
    
    const IP_POOL_ID                    = "ACCOUNT.IP_POOL.ID";
    const IP_POOL_IP_CODE               = "ACCOUNT.IP_POOL.IP_CODE";
    
//    const MESSAGE_COMMON_CODE = "MESSAGE_COMMON_CODE";
//    const CORE_CONFIG_DATA_CODE = "CORE_CONFIG_DATA_CODE";
//    const SYSTEM_CODE_CODE_GROUP_CODE = "SYSTEM_CODE_CODE_GROUP_CODE";
//
//    const TRANSACTION_TRANSACTIONID = 'TRANSACTION_TRANSACTIONID';
//    const TRANSACTION_ID = 'TRANSACTION_ID';
//    const TRANSACTION_ITEM_TRANSACTIONID = 'TRANSACTION_ITEM_TRANSACTIONID';
//    
//    const ROLE_ID = 'ACCOUNT.ROLE_ID';
//    const ROLE_CODE = "ACCOUNT.ROLE_CODE";
//    const ROLE_CODE_GROUP_ID = "ACCOUNT.ROLE_CODE_GROUP_ID";
//    const USER_AUTHORIZATION_USER_PROFILE_ID_TOKEN = "ACCOUNT.USER_AUTHORIZATION_USER_PROFILE_ID_TOKEN";
//    const USER_PROFILE_ID = 'ACCOUNT.USER_PROFILE_ID';
//    const USER_ATTRIBUTE_USER_PROFILE_ID = 'ACCOUNT.USER_ATTRIBUTE_USER_PROFILE_ID';
//    const USER_ATTRIBUTE_USER_PROFILE_ID_ATTRIBUTE_CODE = 'ACCOUNT.USER_ATTRIBUTE_USER_PROFILE_ID_ATTRIBUTE_CODE';
//    const VERSION_CONTROL_APPID = 'ACCOUNT.VERSION_CONTROL_APPID';
//    const VERSION_CONTROL_PLATFORM_APPNAME = 'ACCOUNT.VERSION_CONTROL_PLATFORM_APPNAME';
//    const ACCESS_TOKEN_ID = 'ACCOUNT.ACCESS_TOKEN_ID';
//    const ACCESS_TOKEN_TOKEN = 'ACCOUNT.ACCESS_TOKEN_TOKEN';
//    const ACCESS_TOKEN_LOGIN_ACCOUNT_ID = 'ACCOUNT.ACCESS_TOKEN_LOGIN_ACCOUNT_ID';
//    const ACCESS_TOKEN_LOGIN_ACCOUNT_ID_ACCESS_TYPE_SESSION_TYPE = 'ACCOUNT.ACCESS_TOKEN_LOGIN_ACCOUNT_ID';
//    const LOGIN_ACCOUNT_USER_PROFILE_ID = 'ACCOUNT.LOGIN_ACCOUNT_USER_PROFILE_ID';
//    const LOGIN_ACCOUNT_ID = 'ACCOUNT.LOGIN_ACCOUNT_ID';
//    const USER_ROLE_USER_PROFILE_ID = 'ACCOUNT.USER_ROLE_USER_PROFILE_ID';
//    const ROLE_FUNCTION_ROLE_ID = 'ACCOUNT.ROLE_FUNCTION_ROLE_ID';
//    const ROLE_FUNCTION_ROLE_ID_CODE_DISPLAY_TYPE = 'ACCOUNT.ROLE_FUNCTION_ROLE_ID_CODE_DISPLAY_TYPE';
//    const ROLE_FUNCTION_ROLE_ID_CODE_DISPLAY_TYPE_ACCESS_TYPE = 'ACCOUNT.ROLE_FUNCTION_ROLE_ID_CODE_DISPLAY_TYPE_ACCESS_TYPE';
//    const USER_RELATIONSHIP_USER_PROFILE_ID_RELATIONSHIP_ID = 'ACCOUNT.USER_RELATIONSHIP_USER_PROFILE_ID_RELATIONSHIP_ID';
//    const BLACKLIST_LAST_RECORD_IP_ADDRESS = 'ACCOUNT.BLACKLIST_LAST_RECORD_IP_ADDRESS';
//    const BLACKLIST_LAST_RECORD_USER_PROFILE_ID = 'ACCOUNT.BLACKLIST_LAST_RECORD_USER_PROFILE_ID';
//    const PASSWORD_LOG_USER_PROFILE_ID = 'ACCOUNT.PASSWORD_LOG_USER_PROFILE_ID';
//    const WHITELABEL_PARTNER_CODE = 'ACCOUNT.WHITELABEL_PARTNER_CODE';

}
